version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
